### Listar Todos os Consumos
GET http://localhost:5289/api/consumo/listar

### Criar Novo Registro
POST http://localhost:5289/api/consumo/cadastrar
Content-Type: application/json

{
  "cpf": "123.456.789-00",
  "mes": 10,
  "ano": 2025,
  "m3Consumidos": 37.5,
  "bandeira": "Vermelha",
  "possuiEsgoto": true
}