### Listar Todos os Consumos
GET http://localhost:5289/api/consumo/listar

### Listar Consumo Filtrado
GET http://localhost:5289/api/consumo/buscar/123.456.789-00/8/2025

### Criar Novo Registro
POST http://localhost:5289/api/consumo/cadastrar
Content-Type: application/json

{
  "cpf": "123.456.789-00",
  "mes": 8,
  "ano": 2025,
  "m3Consumidos": 37.5,
  "bandeira": "Vermelha",
  "possuiEsgoto": true
}

### Deletar Registro

DELETE http://localhost:5289/api/consumo/remover/123.456.789-00/9/2025