// <auto-generated />
using CauaTobiasDeSouzaProenca.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CauaTobiasDeSouzaProenca.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20251020225112_AtualizacaoColunasTabela")]
    partial class AtualizacaoColunasTabela
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("Sanepar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("adicionalBandeira")
                        .HasColumnType("REAL");

                    b.Property<int>("ano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("bandeira")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("consumoFaturado")
                        .HasColumnType("REAL");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("m3consumidos")
                        .HasColumnType("REAL");

                    b.Property<int>("mes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("possuiEsgoto")
                        .HasColumnType("INTEGER");

                    b.Property<double>("tarifa")
                        .HasColumnType("REAL");

                    b.Property<double>("taxaEsgoto")
                        .HasColumnType("REAL");

                    b.Property<double>("total")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("Sanepar");
                });
#pragma warning restore 612, 618
        }
    }
}
